### PR TITLE
Added install script instructions

### PR DESCRIPTION
**Pull request by TheodorJ**

### CODE REVIEW

**Comment by zyx-billy** [comment]
cool! Do you want to mention autocomplete installation in the manual install section as well so that devs understand how the autocomplete feature works

**Comment by TheodorJ** [comment]
Oh, that's important. I'll add that in!

**Comment by zyx-billy** [comment]
Added some more headers for a clearer structure, and a bit more info on the build process. But otherwise looks all good :ok_hand:

**Review by zyx-billy — APPROVED** [review]
If you have no more changes to make feel free to squash and merge

**Pull request merged**
